### PR TITLE
Use first sigma in tensor in denoiser callback if only one exists

### PR DESCRIPTION
**Pull request by LoganBooker**
Fixes errors in SD Forge when mode is set to uncond, as the denoiser callback only returns a single sigma. This is a fix for https://github.com/muerrilla/sd-webui-detail-daemon/issues/3.

### CODE REVIEW

**Comment by muerrilla** [comment]
> Fixes errors in SD Forge when mode is set to uncond, as the denoiser callback only returns a single sigma. This is a fix for #3.

Hey there. Thanks! So forge uses the same sigma for the cond and uncond latents? That would mean the `cond` mode would also affect both cond and `uncond` and is basically the same as `both` but without the extra cfg multiplier. This is not the intended `cond` mode. So I think a better way to handle this would be like this (also fixed the unused `multiplier` variable):
```
def denoiser_callback(self, params): 
    if self.is_hires :
        return
    idx = params.denoiser.step   
    multiplier = self.schedule[idx] * .1
    mode = self.mode 
    if params.sigma.size(0) == 1:
        mode = "forge"
        if idx == 0:
            tqdm.write(f'\033[33mINFO:\033[0m Forge does not support `cond` and `uncond` modes')
    if mode == "cond" :
        params.sigma[0] *= 1 - multiplier
    elif mode == "uncond" :
        params.sigma[1] *= 1 + multiplier
    else :
        params.sigma *= 1 - multiplier * self.cfg_scale
```

**Comment by LoganBooker** [comment]
Hi muerilla, that does appear to be the case. Going a bit deeper, Forge just passes the sigma along when sampling and constructing CFGDenoiserParams (https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/main/modules/sd_samplers_cfg_denoiser.py#L153-L180), so you only ever get the one.

I've been using Forge so long I actually didn't realise regular WebUI uses different sigmas for cond and uncond (so was surprised and a bit confused by the error when I encountered it). Under the hood, Forge does a lot of things differently (and a bit strangely) so I'm often finding I'm doing all sorts of odd fixes to get WebUI extensions working in it.

Anyway, your approach is certainly preferable. Feel free to close the pull if you'd just like to put your fix in directly.

**Comment by muerrilla** [comment]
>Forge does a lot of things differently (and a bit strangely) so I'm often finding I'm doing all sorts of odd fixes to get WebUI extensions working in it.

Yeah, I tried porting my personal extensions to forge, but eventually gave up on it all together. So your input was much appreciated.
 
> Anyway, your approach is certainly preferable. Feel free to close the pull if you'd just like to put your fix in directly.

Don't feel like applying it to your pull request yourself and have me merge it? I don't mind either way.

**Comment by LoganBooker** [comment]
Alrighty, that should do it.

**Comment by muerrilla** [comment]
Thanks again.🍻

**Pull request merged**
