### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by w-e-w**
- https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/315#issuecomment-2109846694

---

unnecessary

- [remove unused Imports](https://github.com/muerrilla/sd-webui-detail-daemon/commit/e85e0ab49d5f3e6d6be7edfca447036f4d0a0504)

- [remove unnecessary install script](https://github.com/muerrilla/sd-webui-detail-daemon/commit/3bb43896426f282742e951b28aac9bf5da0e725b)
`numpy` `matplotlib` are sub dependencies of web UI
so there's no point of installing them yourself
`numpy` is it dependency of losts of packages and `matplotlib` is a dependency of `gradio`

---

UI fixes
> there are ways of making your versions work if you prefer your version but this way is simpler

- [switch to InputAccordion](https://github.com/muerrilla/sd-webui-detail-daemon/commit/fbb3f4e74991e82cbf4cefdcf95b7160851016c0)
using the webui custom gradio component InputAccordion an `Accordion with  checkbox`
as opposed to using the custom JavaScript activation color change you've created yourself
image
circumvents the issue where you have multiple elements of the same ID across different tabs causeing togging the `img2img enable` will chenge the color of the `txt2img accordion`

- [use class for css](https://github.com/muerrilla/sd-webui-detail-daemon/commit/0fa632198ee84380ef29f3112f90f3cf9de28ab4)
use class to specify these styles as opposed to using ID, it's also circumvents the issue where you have multiple elements of the same ID across different tabs

---

if for some reason in the future or in other extensions you do need `elem_id` then use [`self.elem_id('XXX')`](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0/modules/scripts.py#L327-L335) to create the id

---

video
<details><summary>before video</summary>
<p>

https://github.com/muerrilla/sd-webui-detail-daemon/assets/40751091/02fda1bc-de8f-4e90-b0e8-a8510b13f87b

</p>
</details> 

<details><summary>after video</summary>
<p>

https://github.com/muerrilla/sd-webui-detail-daemon/assets/40751091/87aa5caf-64d4-45c6-919c-04805b0fe71b

</p>
</details> 

---

optional change
> remove this if you don't like it

- [compact infotext](https://github.com/muerrilla/sd-webui-detail-daemon/commit/ae7dcf78615d1b49951de4a4323cba220a5cbee0)
theres is no issue with the current implementation but I feel like it's taking up lots of space
I feel it makes sence to compact all of the info into one key removing the need of adding so many `DD_xxxxxx` 
note: has [backwards compatibility](https://github.com/muerrilla/sd-webui-detail-daemon/pull/1/commits/ae7dcf78615d1b49951de4a4323cba220a5cbee0#diff-1f32eb4a244add98757d2b939c6a3cb06a55aae1c4cb5b624d5ff60c581e311eR71) with old format

before PR
```
DD_enabled: True, DD_amount: 0.5, DD_start: 0, DD_end: 1, DD_bias: 0.5, DD_exponent: 1, DD_start_offset: 0, DD_end_offset: 0, DD_fade: 0, DD_smooth: True
```
after PR
```
Detail Daemon: "amount:0.5,st:0,ed:1,bias:0.5,exp:1,st_offset:0,ed_offset:0,fade:0,smooth:1"
```
> if you don't like my abbreviations change it

---

I think every commit in this PR is `Cherry Pickable` if you don't like a certain change

### CODE REVIEW

**Comment by muerrilla** [comment]
Hey! Thanks a bunch. ❤ There's a lot to learn here for me.

> I think every commit in this PR is `Cherry Pickable` if you don't like a certain change

I absolutely love all of them, but the InputAccordion might have to go in the next update as I explained [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/315#issuecomment-2110620033) to keep it consistent with other extension. But I'm willing to take it for a spin till then and see if it can change my mind. 😁

**Comment by w-e-w** [comment]
it is possible to make it so that you can choose between InputAccordion or Accordion + checkbox
I have done something similar in the past for backwards compatibility reasons before InputAccordion was introduced in webui

---

also another thing
there is a `default system` in web UI, default values of elements such as sliders will be saved to `ui-config.json`
customization of default values if they find the initial values provided by the developer is not suitable for their use case
the can do so by edit ui-config.json directly or use `settings > defaults` to updata the default values

but this system also has a side effect, if a extension developer later on wishes to change the default value of a element they will NOT be able to do so as the values are already written into `ui-config.json`
> is is possible to force the change by changeing the `lable` of a element because the ID in `ui-config.json` will also change so will no longer be recognized
> I wish we have a better system that allows developer to push changes but also allows user customization at the same time but  unfortunately currently is not the case

this is another reason why the default values should be sensible before releasing it to the masses
as it will be written to any one that has installed this extention

it is possible to disable `default system` this for a specific element if the developer wishes to by adding the `do_not_save_to_config` attribute the a element
```py
# for single element
gr_element.do_not_save_to_config = True
# for a list of elements
elements = [gr_e1, gr_e2, gr_e3]
[setattr(e, 'do_not_save_to_config', True) for e in elements ]
```
but I don't recommend you do so because this would remove the user ability to customise them

however you could disable the `default system` during development phase and re-enable it when you have good default values that can be used by the masses

**Comment by muerrilla** [comment]
> ...where as your use case is more similar to `refine` or `high-res fix` 

True.

> the reason why you see extensions not use InputAccordion that often is mostly becauls old extension may not want to switch because of backwards compatibility consideration the ui uses lots of InputAccordion,

This might indeed be me simply resisting change. 😁 I actually prefer the way the InputAccordion is activated, to the old way of opening the accordion and clicking enable. But the color coding is really crucial for me. I have a long list of extensions and I often need to collapse them the avoid scrolling all day, then I kept forgetting which ones where active quite often. So I made myself a neutral grey theme where the only color on screen are the generation and the active extensions, so I couldn't miss them anymore.

Compare Detail Daemon to the other ones:


What do you think about keeping the InputAccordion but coloring the title on activation? I can imagine that such practice on the grander scale of the extension ecosystem can easily turn the UI into myspace (or was it geocities? the memories are fading), but I think I really need this. The checkbox can easily go though. 

> it is possible to make it so that you can choose between InputAccordion or Accordion + checkbox I have done something similar in the past for backwards compatibility back around the time when InputAccordion was introduced in webui

You mean through the settings tab? I don't know how to do it, but if you did it I would be very happy. This would be ideal solution to the myspace problem. 

---

> also another thing there is a `default system` in web UI

Oh I had never thought about the implications of that.

> this is another reason why the default values should be sensible before releasing it to the masses as it will be written to any one that has installed this extention

Good point.

> however you could disable the `default system` during development phase and re-enable it when you have good default values that can be used by the masses

Great tip. I think the new default values are as good as it gets. It's not easy to come up with good universal values for this thing. I think a more robust solution to this problem is providing presets, which is near the top of my todo list.

---

While we're at it, there seems to be a bug in the new infotext paste functionality. Upon a fresh start or restart, the first time I drop a picture into the prompt box and click the 'read gen params from prompt' button, it works fine. But the times after that it throws this for every DD parameter:
```
*** Error executing <function Script.ui.<locals>.<lambda> at 0x0000021DFCAE8430>
    Traceback (most recent call last):
      File "E:\A1111\stable-diffusion-webui\modules\infotext_utils.py", line 492, in paste_func
        v = key(params)
      File "E:\A1111\stable-diffusion-webui\extensions\sd-webui-detail-daemon\scripts\detail_daemon.py", line 76, in <lambda>
        (gr_start, lambda d: extract_infotext(d, 'st', 'DD_start')),
      File "E:\A1111\stable-diffusion-webui\extensions\sd-webui-detail-daemon\scripts\detail_daemon.py", line 70, in extract_infotext
        return d['Detail Daemon'].get(key)
    AttributeError: 'str' object has no attribute 'get'
```
Can you replicate that?

**Comment by w-e-w** [comment]
> Compare Detail Daemon to the other ones:

lol
> I'm impressed that webui didn't crash with so meny extension

---

> Can you replicate that?

it looks like somehow

https://github.com/muerrilla/sd-webui-detail-daemon/blob/447b915e93c43d217718c15737f501e4b7daa349/scripts/detail_daemon.py#L15-L23

was not executed, very weird
didn't happen to me in my other extensions
let me hava a look later

---

> What do you think about keeping the InputAccordion but coloring the title on activation? I can imagine that such practice on the grander scale of the extension ecosystem can easily turn the UI into myspace (or was it geocities? the memories are fading), but I think I really need this. The checkbox can easily go though.

I think it might be possible to patch in a javascript that change the color on acative for all InputAccordions
I might have a try later and if I manage to do so I might made a standalone extension for those who wants this
> don't let me stop you from doing yourself, I'm not sure if I will be able to succeed

> lol, I seems to have habit of writing extensions that I don't use myself

**Comment by w-e-w** [comment]
@muerrilla 

> While we're at it, there seems to be a bug in the new infotext paste functionality. Upon a fresh start or restart, the first time I drop a picture into the prompt box and click the 'read gen params from prompt' button, it works fine. But the times after that it throws this for every DD parameter:
>
```py
*** Error executing <function Script.ui.<locals>.<lambda> at 0x0000021DFCAE8430>
    Traceback (most recent call last):
      File "E:\A1111\stable-diffusion-webui\modules\infotext_utils.py", line 492, in paste_func
        v = key(params)
      File "E:\A1111\stable-diffusion-webui\extensions\sd-webui-detail-daemon\scripts\detail_daemon.py", line 76, in <lambda>
        (gr_start, lambda d: extract_infotext(d, 'st', 'DD_start')),
      File "E:\A1111\stable-diffusion-webui\extensions\sd-webui-detail-daemon\scripts\detail_daemon.py", line 70, in extract_infotext
        return d['Detail Daemon'].get(key)
    AttributeError: 'str' object has no attribute 'get'
```
> Can you replicate that?

I figured it out this is caused by
`remove_current_script_callbacks()`

**Comment by w-e-w** [comment]
> Compare Detail Daemon to the other ones:

image
what version are you on
on my they have switched to input accordion

**Comment by w-e-w** [comment]
> What do you think about keeping the InputAccordion but coloring the title on activation

I throw together a quick extension to add this
care to have go?
https://github.com/w-e-w/sd-webui-input-accordion-highlightcolor

**Comment by muerrilla** [comment]
> I figured it out this is caused by `remove_current_script_callbacks()`

Oh I see. 

> looked it up, they switch 2 mounts age

Mine is (was) from 2024-03-09. lol!

> I throw together a quick extension to add this

Oooh this is perfect. 👌
So it didn't even need js? huh. Amazing. 

Guess that's bye bye to the old ways then. 😁

**Comment by w-e-w** [comment]
> So it didn't even need js? huh. Amazing

yeah CSS is magic, the `:has()` is a new syntax apparently.

this could be done in pure CSS, Python is just there to allow user customization of the colors

if you want to do something more advanced beyond what I allow in the settings, you could ditch the extension and write your own CSS rule into your own `user.css`

`linear-gradient()` could look nice with some theme

**Pull request merged**
